FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages ./packages
COPY apps/backend ./apps/backend

RUN npm install
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
COPY --from=builder /app ./

EXPOSE 5000

CMD ["npm", "--workspace=@nearwork/backend", "run", "start"]
